### ISSUE TITLE
Compilar SDK de Watson y ver como funciona

### ISSUE THREAD

**Issue by 54BarrosCreations** [54BarrosCreations/Taller-Vertical-2017-ISC-LIN#4]

**Comment by victornjr** [comment]
Ya tengo amigos gracias!!!!

**Comment by victornjr** [comment]
Se descargó el SDK para JS. El plan es utilizar Watson Speech to Text para obtener las respuestas del cliente que esté utilizando la plataforma. La forma es en modo pregunta y respuesta; donde la respuesta se guarda en la base de datos y se comprara después con la información de los doctores.
